# Runs only on pull requests, not commits to branches
trigger: none
jobs:
- template: templates/pr-validation.yml
  parameters:
    pool:
      vmImage: 'macOS-10.15'
    name: 'osx_build'
    e2e: true
- template: templates/pr-validation.yml
  parameters:
    pool:
      vmImage: 'windows-2019'
    name: 'windows_build'
    # TODO XXX skipping e2e on win for now, since spectron doesn't seem to be able to launch the app
    # reliably, even though launching it on its own is reliable.
    # e2e: true
- template: templates/pr-validation.yml
  parameters:
    pool:
      vmImage: 'ubuntu-18.04'
    name: 'linux_build'
    xvfb: true
