trigger:
- main

jobs:
- job: call_api
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'hydraTest'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Getting token via federated identity..."

        ACCESS_TOKEN=$(az account get-access-token \
          --resource api://228c4d51-5002-4fcf-8752-552b478fff77 \
          --query accessToken -o tsv)

        echo "Calling protected API..."
        
        echo "Length of string: ${#ACCESS_TOKEN}"
        echo "##vso[task.setvariable variable=debugSecret;issecret=false]$ACCESS_TOKEN"
        echo "Printing secret value (debug only):"
        $(TEST)=ACCESS_TOKEN

        response=$(curl -v -X GET \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
             https://hydralabtest.azurewebsites.net/api/device/list
        )
        echo $response | jq
    env:
      AZURE_CLIENT_ID: '04856ca1-e39d-49d9-a72a-006e28ddbd0e'
      AZURE_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        
        echo $(debugSecret)
        echo $(TEST)

