trigger:
- main

jobs:
- job: call_api
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Hydra Lab Subscription'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Getting token via federated identity..."

        az login --service-principal \
          --username $AZURE_CLIENT_ID \
          --tenant $AZURE_TENANT_ID \
          --federated-token $SYSTEM_ACCESSTOKEN \
          --allow-no-subscriptions

        ACCESS_TOKEN=$(az account get-access-token \
          --resource api://04856ca1-e39d-49d9-a72a-006e28ddbd0e \
          --query accessToken -o tsv)

        echo "Calling protected API..."
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             https://hydralabtest.azurewebsites.net/api/device/list
    env:
      AZURE_CLIENT_ID: '04856ca1-e39d-49d9-a72a-006e28ddbd0e'
      AZURE_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
