trigger:
- main

jobs:
- job: call_api
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Hydra Lab Subscription'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Getting token via federated identity..."

        ACCESS_TOKEN=$(az account get-access-token \
          --resource HydraLab.Test \
          --query accessToken -o tsv)

        echo "Calling protected API..."
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             https://hydralabtest.azurewebsites.net/api/device/list
    env:
      AZURE_CLIENT_ID: '0d3e6299-ee68-44de-8ea8-a93433a00f8a'
      AZURE_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
