trigger:
- main

jobs:
- job: call_api
  pool:
    name: YP_Performance_Test
    demands:
      - Agent.Name -equals MININT-T69DC43
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'hydraTest'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Getting token via federated identity..."
        $ACCESS_TOKEN=az account get-access-token --query accessToken --resource=https://database.windows.net -o tsv

        echo "Calling protected API..."
        
        echo "Length of string: ${#ACCESS_TOKEN}"
        New-Item -Path sdk -Name ".env" -ItemType "file" -Value "DB_TOKEN=$ACCESS_TOKEN"
       
        echo $ACCESS_TOKEN | cut -d "." -f2 | base64 -d | jq
        
        $headers = @{
            "Content-Type"  = "application/json"
            "Authorization" = "Bearer $ACCESS_TOKEN"
        }

        $response = Invoke-RestMethod -Uri "https://hydralabtest.azurewebsites.net/api/device/list" `
                                      -Method Get `
                                      -Headers $headers

        $response | ConvertTo-Json -Depth 10

    env:
      AZURE_CLIENT_ID: '04856ca1-e39d-49d9-a72a-006e28ddbd0e'
      AZURE_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

