@startuml
'https://plantuml.com/class-diagram'

package "sdk" {

    class PerformanceTestSpec {
        +{static}String TYPE_ANDROID_MEMORY_DUMP = "AndroidMemoryDump"
        +{static}String TYPE_ANDROID_MEMORY_INFO = "AndroidMemoryInfo"
        +{static}String TYPE_ANDROID_BATTERY_INFO = "AndroidBatteryInfo"
        +{static}String TYPE_WIN_BATTERY = "WindowsBattery"
        +{static}String TYPE_WIN_MEMORY = "WindowsMemory"
        -List<String> typeSpecList
        -String appId
        -String deviceId
        -String stepName
        +constructor()
        +getter()
        +setter()
    }
    interface PerformanceInspector {
        void initialize(PerformanceTestSpec performanceTestSpec, File resultFolder)
        PerformanceInspectionResult inspect(PerformanceTestSpec performanceTestSpec, File resultFolder)
        PerformanceResult<?> parse(List<PerformanceInspectionResult> performanceInspectionResultList)
    }

    class PerformanceInspectionService {
        File resultFolder
        List<PerformanceRecorder> inspectors
        List<PerformanceInspectionResult> performanceInspectionResultList
        List<ScheduledFuture<?>> inspectPerformanceTimerList
        {static} ScheduledExecutorService timerExecutor
        +void addInspector(PerformanceInspector performanceRecorder)
        -void notifyEach()
        +void initialize(PerformanceTestSpec performanceTestSpec)
        +void startInspectPerformanceTimer((PerformanceTestSpec performanceTestSpec, long interval)
        +void inspect(PerformanceTestSpec performanceTestSpec)
        +List<PerformanceResult<?>> parse()
    }

    class PerformanceResult {
        String category
        T performanceData
        List<PerformanceInspectionResult> performanceInspectionResultList
    }

    class PerformanceInspectionResult {
        String type;
        File profilingRawResultFile;
    }


    PerformanceInspector -left..> PerformanceTestSpec
    PerformanceInspector -up..> PerformanceInspectionResult
    PerformanceInspector <---right PerformanceInspectionService
    PerformanceInspector -up..> PerformanceResult
    PerformanceResult -right..> PerformanceInspectionResult
}

package "common" {
    class PerformanceInspectorManager {
        AndroidBatteryInspector androidBatteryInspector;
        AndroidMemoryInfoInspector androidMemoryInfoInspector;
        AndroidMemoryDumpInspector androidMemoryDumpInspector;
        WindowsBatteryInspector windowsBatteryInspector;
        WindowsMemoryInspector windowsMemoryInspector;
    }
    PerformanceInspector <|-- AndroidBatteryInspector
    PerformanceInspector <|-- AndroidMemoryInfoInspector
    PerformanceInspector <|-- AndroidMemoryDumpInspector
    PerformanceInspector <|-- WindowsBatteryInspector
    PerformanceInspector <|-- WindowsMemoryInspector

    AndroidBatteryInspector --o PerformanceInspectorManager
    AndroidMemoryInfoInspector --o PerformanceInspectorManager
    AndroidMemoryDumpInspector --o PerformanceInspectorManager
    WindowsBatteryInspector --o PerformanceInspectorManager
    WindowsMemoryInspector --o PerformanceInspectorManager

    TestRunner o-r- PerformanceInspectorManager
}
@enduml

@startuml
participant PerformanceManager
participant Runner
participant PerformanceInspectionService
participant AndroidMemoryInfoInspector
participant AndroidBatteryInfoInspector
participant WindowsBatteryInspector

title Sequence 1: Regularly inspect performance metrics

PerformanceManager -> PerformanceManager: new Inspectors
activate Runner
Runner -> PerformanceInspectionService : new PerformanceInspectionService()
activate PerformanceInspectionService
Runner -> PerformanceManager: get Inspectors
PerformanceManager -> Runner: Inspectors
Runner -> PerformanceInspectionService : add Inspectors
Runner -> PerformanceInspectionService : startInspectPerformanceTimer(performanceTestSpec, interval)
PerformanceInspectionService -> AndroidMemoryInfoInspector : initialize
PerformanceInspectionService -> AndroidBatteryInfoInspector : initialize
PerformanceInspectionService -> WindowsBatteryInspector : initialize
PerformanceInspectionService -> AndroidMemoryInfoInspector : inspect
AndroidMemoryInfoInspector -> PerformanceInspectionService : PerformanceInspectionResult
PerformanceInspectionService -> AndroidBatteryInfoInspector : inspect
AndroidBatteryInfoInspector -> PerformanceInspectionService : PerformanceInspectionResult
PerformanceInspectionService -> WindowsBatteryInspector : inspect
WindowsBatteryInspector -> PerformanceInspectionService : PerformanceInspectionResult
Runner -> PerformanceInspectionService : parse
PerformanceInspectionService -> AndroidMemoryInfoInspector : parse
AndroidMemoryInfoInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> AndroidBatteryInfoInspector : parse
AndroidBatteryInfoInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> WindowsBatteryInspector : parse
WindowsBatteryInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> Runner: List<PerformanceResult>
deactivate PerformanceInspectionService
deactivate Runner
@enduml

@startuml
participant PerformanceManager
participant Runner
participant TestCase
participant PerformanceInspectionService
participant AndroidMemoryInfoInspector
participant AndroidBatteryInfoInspector
participant WindowsBatteryInspector
participant ThreadParam

title Sequence 2: Trigger performance metrics inspection by test case

PerformanceManager -> PerformanceManager: new Inspectors
activate Runner
Runner -> PerformanceInspectionService : new PerformanceInspectionService()
activate PerformanceInspectionService
Runner -> PerformanceManager: get Inspectors
PerformanceManager -> Runner: Inspectors
Runner -> PerformanceInspectionService : add Inspectors
Runner -> ThreadParam: init(..., PerformanceInspectionService)
activate ThreadParam
Runner -> TestCase : execute
activate TestCase
TestCase -> ThreadParam : getPerformanceInspectionService
ThreadParam -> TestCase : PerformanceInspectionService
TestCase -> PerformanceInspectionService : initialize
PerformanceInspectionService -> AndroidMemoryInfoInspector : initialize
PerformanceInspectionService -> AndroidBatteryInfoInspector : initialize
PerformanceInspectionService -> WindowsBatteryInspector : initialize
TestCase -> PerformanceInspectionService : inspect
PerformanceInspectionService -> AndroidMemoryInfoInspector : inspect
AndroidMemoryInfoInspector -> PerformanceInspectionService : PerformanceInspectionResult
PerformanceInspectionService -> AndroidBatteryInfoInspector : inspect
AndroidBatteryInfoInspector -> PerformanceInspectionService : PerformanceInspectionResult
PerformanceInspectionService -> WindowsBatteryInspector : inspect
WindowsBatteryInspector -> PerformanceInspectionService : PerformanceInspectionResult
PerformanceInspectionService -> TestCase : List<PerformanceInspectionResult>
TestCase -> Runner: return
deactivate
Runner -> PerformanceInspectionService : parse
PerformanceInspectionService -> AndroidMemoryInfoInspector : parse
AndroidMemoryInfoInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> AndroidBatteryInfoInspector : parse
AndroidBatteryInfoInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> WindowsBatteryInspector : parse
WindowsBatteryInspector -> PerformanceInspectionService : PerformanceResult
PerformanceInspectionService -> Runner: List<PerformanceResult>
deactivate PerformanceInspectionService
Runner -> ThreadParam: clean
deactivate ThreadParam
deactivate Runner
@enduml