# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Clean Cache'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder'
    customCommand: 'cache clean --force'

- task: Npm@1
  displayName: 'Install npm package'
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder'
    verbose: true

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder'
    customCommand: 'run build:prod:main'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder'
    customCommand: 'run build:prod:renderer'
- task: Npm@1
  displayName: 'Package'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder'
    customCommand: 'run package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder\release\Tap_to_Cases-windows.exe'
    ArtifactName: 'release'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\taps_to_cases\T2C_Recorder\release\Tap_to_Cases-windows.zip'
    ArtifactName: 'release'
    publishLocation: 'Container'