@startuml storage_sequence
'(Local, Azure BLOB, ALI Cloud, QINIU Cloud, etc.)
autonumber 1.1
StorageService -> Center.StorageServiceClient: buildClient(connectionString)
Center.StorageServiceClient -> Storage.ServiceEndpoint: upload(screenshot / attachment / agentPackage)
Storage.ServiceEndpoint --> Center.StorageServiceClient: uploaded file info
Center.StorageServiceClient -> Storage.ServiceEndpoint: download(jsonFile)
Storage.ServiceEndpoint --> Center.StorageServiceClient: downloaded file info
|||
autonumber 2.1
Center.StorageServiceClient -> Browser: generateReadToken
Browser -> Storage.ServiceEndpoint: read files with token
|||
autonumber 3.1
Center.StorageServiceClient -> AgentMetadata: generateWriteToken
activate AgentMetadata
AgentMetadata -> Agent.StorageServiceClient: heartbeatResponse(accessToken)
deactivate AgentMetadata
StorageService -> Agent.StorageServiceClient: buildClient(accessToken)
Agent.StorageServiceClient -> Storage.ServiceEndpoint: download(app / testApp / attachment / agentPackage)
Storage.ServiceEndpoint -> Agent.StorageServiceClient: downloaded file info
Agent.StorageServiceClient -> Storage.ServiceEndpoint: upload(deviceTestResult)
Storage.ServiceEndpoint -> Agent.StorageServiceClient: uploaded file info

@enduml
