app:
  # register to Hydra Lab Center
  registry:
    # The server hostname:port of Hydra Lab Center. If nginx enabled, switch to port of nginx
    server: 'localhost:9886'
    # The Agent info registered in Hydra Lab Center, for instance if it's running on localhost, the URL would be: http://localhost:9886/portal/index.html#/auth
    name: {YOUR_AGENT_NAME}
    id: {YOUR_REGISTERED_AGENT_ID}
    secret: {YOUR_REGISTERED_AGENT_SECRET}
  device:
    monitor:
      windows:
        enabled: false
      android:
        enabled: true
      ios:
        enabled: false