spring:
  datasource:
    url: jdbc:sqlite:${app.location}/hydra_lab_uber_center_db.sqlite

app:
  location: /hydra/data
  storage:
    type: ${STORAGE_TYPE:LOCAL} # current available options: LOCAL, AZURE