spring:
  datasource:
    url: jdbc:sqlite:${app.location}/hydra_lab_center_docker_db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sqlite
    password: 98765432

app:
  location: /hydra/data